
# Default sed regexp - multiline due to syntax constraints
define sed-y
    "/^->/{s:->#\(.*\):/* \1 */:; \
    s:^->\([^ ]*\) [\$$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; \
    s:^->\([^ ]*\) [\$$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; \
    s:->::; p;}"
endef

define offsets
    (set -e; \
     echo "#ifndef __ASM_OFFSETS_H__"; \
     echo "#define __ASM_OFFSETS_H__"; \
     echo "/*"; \
     echo " * DO NOT MODIFY."; \
     echo " *"; \
     echo " * This file was generated by kernel.mk from linux-3.17/Kbuild"; \
     echo " *"; \
     echo " */"; \
     echo ""; \
     sed -ne $(sed-y) $(out_dir)/offsets.s; \
     echo ""; \
     echo "#endif" ) > $@
endef
 

offsets.h : x86-offsets.def
	$Q cp $^ $(out_dir)/offsets.c
	$Q echo $(CC) -S $(out_dir)/offsets.c -I./ $(c_flags) -o $(out_dir)/offsets.s
	$Q      $(CC) -S $(out_dir)/offsets.c -I./ $(c_flags) -o $(out_dir)/offsets.s
	$Q $(offsets)

x86.S : offsets.h
