#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by kernel.mk from linux-3.17/Kbuild
 *
 */

#define core 180 /* offsetof(struct _task, core) */
#define registers 176 /* offsetof(struct _task, registers) */

#endif
